"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:#106ebe)\
$os\
$username\
[](fg:#106ebe bg:#ffffff)\
$hostname\
[](fg:#ffffff bg:#2b2d34)\
$directory\
[](fg:#2b2d34) \
"""

add_newline = true

[os]
style = "bg:#106ebe"
format = "[$symbol]($style)"
disabled = false

[username]
show_always = true
style_user = "bg:#106ebe fg:#ffffff"
style_root = "bg:#106ebe fg:#ff3333"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = false
format = "[ 💻 $hostname ](bg:#ffffff fg:#106ebe)"
disabled = false

[directory]
format = '[ 📂 $path](bg:#2b2d34 fg:#67fff0)'
